### ISSUE TITLE
Need to add issuer field to assets

### ISSUE THREAD

**Issue by msfeldstein** [stellar/stellar-anchor-server#77]
When creating an asset, we need to supply an issuer instead of just a name.  This will show up in the toml file

**Comment by debnil** [comment]
@accordeiro and I talked about this in the context of #73: since this is an anchor server, the issuer address would be the `STELLAR_ACCOUNT_ADDRESS` set in the virtual environment and defined in `django.conf.settings` through `app/settings.py`. That should be populated in the TOML file (created via #81) as well.

**Comment by debnil** [comment]
Closed via #81.
